// Generated by Wrangler by running `wrangler types`

interface Env {
	INDEX: "https://ggpk-index.onrender.com";
	EXTRACTOR: "https://unoodler.lvlvlvllvlvlvl.workers.dev";
	IMAGES: "https://image.ggpk.exposed";
	BROWSER: "https://www.ggpk.exposed";
}
