// Generated by Wrangler by running `wrangler types`

interface Env {
	EXTRACTOR: "https://unoodler.lvlvlvllvlvlvl.workers.dev";
	IMAGES: "https://image.ggpk.exposed";
	BROWSER: "https://www.ggpk.exposed";
	poe1: D1Database;
	poe2: D1Database;
}
