#:schema node_modules/wrangler/config-schema.json
name = "ggpker"
main = "src/index.ts"
compatibility_date = "2025-06-14"

routes = [
	{ pattern = "ggpk.exposed", custom_domain = true }
]

[dev]
port = 8788

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[vars]
BROWSER = "https://www.ggpk.exposed"
IMAGES = "https://i.ggpk.exposed"

[[services]]
binding = "EXTRACTOR"
service = "unoodler"

[[services]]
binding = "INDEX"
service = "ggpk-index-server"
