#:schema node_modules/wrangler/config-schema.json
name = "ggpker"
main = "src/index.ts"
compatibility_date = "2025-06-14"

routes = [
	{ pattern = "ggpk.exposed", custom_domain = true }
]

[dev]
port = 8788

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[vars]
EXTRACTOR = "https://unoodler.lvlvlvllvlvlvl.workers.dev"
IMAGES = "https://image.ggpk.exposed"
BROWSER = "https://www.ggpk.exposed"

[env.local.vars]
EXTRACTOR = "http://localhost:8787"
IMAGES = "http://localhost:8789"
BROWSER = "http://localhost:5173"

[[d1_databases]]
binding = "poe1"
database_name = "poe1-files"
database_id = "21ad1cac-ffe5-4582-9c98-c5ddd59594fe"

[[d1_databases]]
binding = "poe2"
database_name = "poe2-files"
database_id = "accb4c83-f64f-40bd-9f99-73130ef53e3a"

