#:schema node_modules/wrangler/config-schema.json
name = "ggpker"
main = "src/index.ts"
compatibility_date = "2025-06-14"

routes = [
	{ pattern = "ggpk.exposed", custom_domain = true }
]

[dev]
port = 8788

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[vars]
EXTRACTOR = "https://unoodler.lvlvlvllvlvlvl.workers.dev"
IMAGES = "https://image.ggpk.exposed"
BROWSER = "https://www.ggpk.exposed"
INDEX = "https://ggpk-index-server.lvlvlvllvlvlvl.workers.dev"

[env.local.vars]
EXTRACTOR = "http://localhost:8787"
IMAGES = "http://localhost:8789"
BROWSER = "http://localhost:5173"
INDEX = "http://localhost:3000"

[[services]]
binding = "INDEX_SERVICE"
service = "ggpk-index-server"

[[env.local.services]]
binding = "INDEX_SERVICE"
service = "ggpk-index-server"

